package android.com.aiface.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import android.com.aiface.database.bean.HomeFace;
import android.com.aiface.database.bean.MeetingFace;
import android.com.aiface.database.bean.GateFace;
import android.com.aiface.database.bean.AttendanceFace;

import android.com.aiface.greendao.HomeFaceDao;
import android.com.aiface.greendao.MeetingFaceDao;
import android.com.aiface.greendao.GateFaceDao;
import android.com.aiface.greendao.AttendanceFaceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeFaceDaoConfig;
    private final DaoConfig meetingFaceDaoConfig;
    private final DaoConfig gateFaceDaoConfig;
    private final DaoConfig attendanceFaceDaoConfig;

    private final HomeFaceDao homeFaceDao;
    private final MeetingFaceDao meetingFaceDao;
    private final GateFaceDao gateFaceDao;
    private final AttendanceFaceDao attendanceFaceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeFaceDaoConfig = daoConfigMap.get(HomeFaceDao.class).clone();
        homeFaceDaoConfig.initIdentityScope(type);

        meetingFaceDaoConfig = daoConfigMap.get(MeetingFaceDao.class).clone();
        meetingFaceDaoConfig.initIdentityScope(type);

        gateFaceDaoConfig = daoConfigMap.get(GateFaceDao.class).clone();
        gateFaceDaoConfig.initIdentityScope(type);

        attendanceFaceDaoConfig = daoConfigMap.get(AttendanceFaceDao.class).clone();
        attendanceFaceDaoConfig.initIdentityScope(type);

        homeFaceDao = new HomeFaceDao(homeFaceDaoConfig, this);
        meetingFaceDao = new MeetingFaceDao(meetingFaceDaoConfig, this);
        gateFaceDao = new GateFaceDao(gateFaceDaoConfig, this);
        attendanceFaceDao = new AttendanceFaceDao(attendanceFaceDaoConfig, this);

        registerDao(HomeFace.class, homeFaceDao);
        registerDao(MeetingFace.class, meetingFaceDao);
        registerDao(GateFace.class, gateFaceDao);
        registerDao(AttendanceFace.class, attendanceFaceDao);
    }
    
    public void clear() {
        homeFaceDaoConfig.clearIdentityScope();
        meetingFaceDaoConfig.clearIdentityScope();
        gateFaceDaoConfig.clearIdentityScope();
        attendanceFaceDaoConfig.clearIdentityScope();
    }

    public HomeFaceDao getHomeFaceDao() {
        return homeFaceDao;
    }

    public MeetingFaceDao getMeetingFaceDao() {
        return meetingFaceDao;
    }

    public GateFaceDao getGateFaceDao() {
        return gateFaceDao;
    }

    public AttendanceFaceDao getAttendanceFaceDao() {
        return attendanceFaceDao;
    }

}
