package android.com.aiface.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import android.com.aiface.database.bean.GateFace;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GATE_FACE".
*/
public class GateFaceDao extends AbstractDao<GateFace, Long> {

    public static final String TABLENAME = "GATE_FACE";

    /**
     * Properties of entity GateFace.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FacePath = new Property(1, String.class, "facePath", false, "FACE_PATH");
        public final static Property UserName = new Property(2, String.class, "userName", false, "USER_NAME");
    }


    public GateFaceDao(DaoConfig config) {
        super(config);
    }
    
    public GateFaceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GATE_FACE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"FACE_PATH\" TEXT NOT NULL ," + // 1: facePath
                "\"USER_NAME\" TEXT NOT NULL );"); // 2: userName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GATE_FACE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GateFace entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getFacePath());
        stmt.bindString(3, entity.getUserName());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GateFace entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getFacePath());
        stmt.bindString(3, entity.getUserName());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GateFace readEntity(Cursor cursor, int offset) {
        GateFace entity = new GateFace( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // facePath
            cursor.getString(offset + 2) // userName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GateFace entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFacePath(cursor.getString(offset + 1));
        entity.setUserName(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GateFace entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GateFace entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GateFace entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
