package android.com.aiface.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import android.com.aiface.database.bean.HomeFace;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOME_FACE".
*/
public class HomeFaceDao extends AbstractDao<HomeFace, Long> {

    public static final String TABLENAME = "HOME_FACE";

    /**
     * Properties of entity HomeFace.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property HomeAddr = new Property(1, String.class, "homeAddr", false, "HOME_ADDR");
        public final static Property HostName = new Property(2, String.class, "hostName", false, "HOST_NAME");
        public final static Property UserId = new Property(3, String.class, "userId", false, "USER_ID");
        public final static Property GustName = new Property(4, String.class, "gustName", false, "GUST_NAME");
        public final static Property VisitTime = new Property(5, String.class, "visitTime", false, "VISIT_TIME");
    }


    public HomeFaceDao(DaoConfig config) {
        super(config);
    }
    
    public HomeFaceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOME_FACE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"HOME_ADDR\" TEXT NOT NULL ," + // 1: homeAddr
                "\"HOST_NAME\" TEXT NOT NULL ," + // 2: hostName
                "\"USER_ID\" TEXT NOT NULL ," + // 3: userId
                "\"GUST_NAME\" TEXT," + // 4: gustName
                "\"VISIT_TIME\" TEXT);"); // 5: visitTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOME_FACE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HomeFace entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getHomeAddr());
        stmt.bindString(3, entity.getHostName());
        stmt.bindString(4, entity.getUserId());
 
        String gustName = entity.getGustName();
        if (gustName != null) {
            stmt.bindString(5, gustName);
        }
 
        String visitTime = entity.getVisitTime();
        if (visitTime != null) {
            stmt.bindString(6, visitTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HomeFace entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getHomeAddr());
        stmt.bindString(3, entity.getHostName());
        stmt.bindString(4, entity.getUserId());
 
        String gustName = entity.getGustName();
        if (gustName != null) {
            stmt.bindString(5, gustName);
        }
 
        String visitTime = entity.getVisitTime();
        if (visitTime != null) {
            stmt.bindString(6, visitTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HomeFace readEntity(Cursor cursor, int offset) {
        HomeFace entity = new HomeFace( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // homeAddr
            cursor.getString(offset + 2), // hostName
            cursor.getString(offset + 3), // userId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // gustName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // visitTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HomeFace entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHomeAddr(cursor.getString(offset + 1));
        entity.setHostName(cursor.getString(offset + 2));
        entity.setUserId(cursor.getString(offset + 3));
        entity.setGustName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setVisitTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HomeFace entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HomeFace entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HomeFace entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
